language: python
python:
  - "3.5"
install:
  - pip install numpy
  - pip install sympy
  - pip install quadpy
  - pip install scipy
  - pip install coveralls
  - pip install pytest-cov
  - python setup.py install
script:
  - pytest --cov SSplines/
after_success:
  - coveralls
